---
- name: Configuring tomcat10 on nodes
  hosts: all
  tasks:
    - name: install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: install tomcat-admin
      apt: 
        name: tomcat10-admin
        state: present
        update_cache: no
    - name: copy tomcat-users.xml
      copy:
        src: /home/ubuntu/playbooks/tomcat-users.xml
        dest: /etc/tomcat10
    - name: replcae ports
      replace:
        regexp: 9999
        replace: 8888
        path: /etc/tomcat10/server.xml
    - name: restart the service
      service:
        name: tomcat10
        state: restarted
    - name: pause for 1 sec
      pause:
        minutes: 1
    - name: check url of server1
      uri:
        url: http://172.31.92.132:8888/
        status_code: 200
    - name: check url of server2
      uri:
        url: http://172.31.87.13:8888/
        status_code: 200
...
