---
- name:
  apt:
    name: "{{item.a}}"
    state: "{{item.b}}"
    update_cache: "{{item.c}}"
  with_items:
    - {a: "{{t}}",b: "{{st}}",c: "{{chy}}"}
    - {a: "{{t10}}",b: "{{st}}",c: "{{chn}}"}
...

